#!/bin/sh
set -e

CERT_DIR=/etc/h2o
STATIC_DIR=/srv/static

mkdir -p "$CERT_DIR" "$STATIC_DIR"

# ── TLS certificate ────────────────────────────────────────────────────────
if [ ! -f "$CERT_DIR/server.crt" ]; then
    echo "[entrypoint] Generating self-signed TLS certificate..."
    openssl req -x509 -newkey rsa:2048 \
        -keyout "$CERT_DIR/server.key" \
        -out "$CERT_DIR/server.crt" \
        -days 3650 -nodes \
        -subj "/CN=server" \
        -addext "subjectAltName=DNS:server,DNS:localhost,IP:127.0.0.1"
    echo "[entrypoint] Certificate generated."
fi

# ── Payload files ──────────────────────────────────────────────────────────
# Primary: files are pre-generated by scripts/generate-payloads.sh and
# mounted via the docker-compose volume (./payloads:/srv/static).
# Fallback: generate any missing files so the server always has content.

gen() {
    path="$1" bs="$2" count="$3"
    [ -f "$path" ] && return
    echo "[entrypoint] Generating missing payload: $path"
    dd if=/dev/zero "of=$path" "bs=$bs" "count=$count" 2>/dev/null
}

gen "$STATIC_DIR/100kb.bin"       1K    100
gen "$STATIC_DIR/1mb.bin"         1M    1
gen "$STATIC_DIR/5mb.bin"         1M    5
gen "$STATIC_DIR/small_page.bin"  1K    470
gen "$STATIC_DIR/medium_page.bin" 1K    1536
gen "$STATIC_DIR/large_page.bin"  1K    2867

echo "[entrypoint] Payload files in $STATIC_DIR:"
ls -lh "$STATIC_DIR"

echo "[entrypoint] Starting h2o..."
exec h2o -c /etc/h2o/h2o.conf
